### ISSUE TITLE
Just one more bit of extreme pickiness

### ISSUE THREAD

**Issue by charleslparker** [whizzml/whizzml-mode#5]
In my editor, the leading paren for all of the `if`, `let`, `when`, `lambda`, `map`, `filter` calls is highlighted with the keyword, for every keyword, it seems *except* `define`!

**Comment by jaor** [comment]
good catch, looking into it.

**Comment by jaor** [comment]
pushed a patch that should fix the issue.

**Comment by charleslparker** [comment]
Impressive turnaround!
